// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_kdXCxgiZgxwBXYj7PGovl3pvdiSIQY',
    appId: '1:572413752865:web:ad16090fce7caea4ce1560',
    messagingSenderId: '572413752865',
    projectId: 'fir-firebase-c3208',
    authDomain: 'fir-firebase-c3208.firebaseapp.com',
    storageBucket: 'fir-firebase-c3208.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvjj-7Agj0Iu2c6on2vp-eMVOOhgwoRuQ',
    appId: '1:572413752865:android:5cb1154cfdd4a087ce1560',
    messagingSenderId: '572413752865',
    projectId: 'fir-firebase-c3208',
    storageBucket: 'fir-firebase-c3208.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPuKdaDwlZMT7nc1pLe1YlpCThspEvidI',
    appId: '1:572413752865:ios:88a74b4c95ead789ce1560',
    messagingSenderId: '572413752865',
    projectId: 'fir-firebase-c3208',
    storageBucket: 'fir-firebase-c3208.firebasestorage.app',
    iosBundleId: 'com.example.session5',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPuKdaDwlZMT7nc1pLe1YlpCThspEvidI',
    appId: '1:572413752865:ios:88a74b4c95ead789ce1560',
    messagingSenderId: '572413752865',
    projectId: 'fir-firebase-c3208',
    storageBucket: 'fir-firebase-c3208.firebasestorage.app',
    iosBundleId: 'com.example.session5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd_kdXCxgiZgxwBXYj7PGovl3pvdiSIQY',
    appId: '1:572413752865:web:1c587c2cddd0da96ce1560',
    messagingSenderId: '572413752865',
    projectId: 'fir-firebase-c3208',
    authDomain: 'fir-firebase-c3208.firebaseapp.com',
    storageBucket: 'fir-firebase-c3208.firebasestorage.app',
  );
}
